DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
CALLE VARCHAR(100) NOT NULL,
NUMERO VARCHAR(20) NOT NULL,
LOCALIDAD VARCHAR(20) NOT NULL,
PROVINCIA VARCHAR(20) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
APELLIDO VARCHAR(100) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
DOCUMENTO VARCHAR(100) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
DOMICILIO_ID INT NOT NULL,
EMAIL VARCHAR(100));

DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NRO_MATRICULA VARCHAR(100) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO VARCHAR(100) NOT NULL);

INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('QUINTANA', '2437', 'CORRIENTES', 'CORRIENTES');
INSERT INTO PACIENTES (APELLIDO,NOMBRE,DOCUMENTO,FECHA_INGRESO,DOMICILIO_ID,EMAIL) VALUES ('MARTINEZ','LEANDRO','32135432','2023-03-13',1,'lean3dro@gmail.com');
INSERT INTO ODONTOLOGOS (NRO_MATRICULA,NOMBRE,APELLIDO) VALUES ('12321', 'rodol', 'ezq');